name: Build and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  build-push:
    name: Build and Push 
    runs-on: ubuntu-latest
    env:
      PHP_VERSION: 8.2-fpm
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setting image tag based on SHA
      run: |
        echo "IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
        # echo "IMAGE_TAG=latest" >> $GITHUB_ENV

    - uses: satackey/action-docker-layer-caching@v0.0.11
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true     
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      # id: buildx
      uses: docker/setup-buildx-action@v3
        # with:
        #   install: true
    # Login to Docker registry
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_ID }}
        password: ${{ secrets.DOCKER_PW }}

    - name: Set Docker Image
      # if: ${{ false }}
      run: |
        sed -i 's/FROM php:php-var-alpine/FROM php:${{ env.PHP_VERSION }}-alpine/g' Dockerfile
            
    # Multi architecture build and push
    - name: Build and push application
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        file: ./Dockerfile
        tags: k4mrul/php-${{ env.PHP_VERSION }}-alpine-wordpress:${{ env.IMAGE_TAG }}
        platforms: linux/arm64,linux/amd64
