name: Build and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check if it's a release from main
      if: github.ref_name == 'main' && github.event_name == 'release'
      run: |
        echo "This is a release event from the main branch"

    # Add your build/test/deploy steps here
    - name: Run Main only
      if: github.ref_name == 'main'
      run: |
        echo "This is just main push"

    # You can add more steps as needed for your workflow

